### ISSUE TITLE
11th degree sorted incorrectly on chord creation

### ISSUE THREAD

**Issue by xavriley** [andreamust/harte-library#18]
This is fixed by #17 which explains the details - I'm just creating an issue for visibility in case anyone else runs into this in the meantime

**Comment by andreamust** [comment]
Thanks @xavriley for contributing!
Fix #17 has been merged in c6f2641c464b851cf1450d4e52e7b1e1e80f0b49 and a new release has been uploaded on PyPi (v0.3.1).
